version: "3"
services:
  app:
    image: fb11-demo:latest
    links:
      - db
      - memcached
    environment:
      PSGI: /opt/perl5/bin/fb11-demo.psgi

  db:
    image: postgres:10.1
    volumes:
      - './pgdata:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: fb11
      POSTGRES_PASSWORD: fb11password

  memcached:
    image: memcached
